version: '3'
services:
  app:
    build: .
    ports:
      - "5153:5153"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: postgres
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
      # - ../db:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_db:
    name: 2f36c6a094e876305e7be166c7c1bc57d395f7db77de215a7baa2027cbd35b6a # use existing volume
    external: true
